version: '2'
services:
    movietracker-app:
        image: movietracker
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:sqlserver://movietracker-mssql:1433;database=MovieTracker
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    movietracker-mssql:
        extends:
            file: mssql.yml
            service: movietracker-mssql
